// Sourced numbers for the dashboard. Every number here is quoted in
// xbm-nightly/2026-10-07/pick.md, which cites Nutrient's 2026-10-06 Readwise brief.
// Do not add numbers that are not in those sources.

export type Source = {
  title: string
  author: string
  note: string
}

export const SOURCES = {
  jev: {
    title: "A New Kind of AI Model: Jev and Quick Wins for PMs",
    author: "Paweł Huryn, The Product Compass",
    note: "via Nutrient's Readwise brief, 2026-10-06",
  },
  semi: {
    title: "Anthropic Subscriptions Offer 5x+ More Value Than OpenAI",
    author: "SemiAnalysis",
    note: "via Nutrient's Readwise brief, 2026-10-06",
  },
  xbm: {
    title: "yishan/xbm git history (merged PRs on main)",
    author: "github.com/yishan/xbm",
    note: "generated by scripts/gen-timeline.ts, dates in Asia/Shanghai",
  },
} satisfies Record<string, Source>

/** Jev latency measured by the author: N questions asked in one call. */
export type LatencyRow = { label: string; questions: number; ms: number }
export const JEV_LATENCY: LatencyRow[] = [
  { label: "1 question", questions: 1, ms: 603 },
  { label: "32 questions", questions: 32, ms: 566 },
]

/** Jev compliance with an internal rule, out of 24 runs. */
export type ComplianceRow = { label: string; followed: number; total: number }
export const JEV_COMPLIANCE: ComplianceRow[] = [
  { label: "Rule in prompt", followed: 24, total: 24 },
  { label: "Rule not in prompt", followed: 5, total: 24 },
]

/** Jev moderation cost per item (about). */
export const JEV_COST_PER_ITEM_USD = 0.00002

/** API-equivalent value used on a $200 subscription plan (SemiAnalysis). */
export type PlanValueRow = {
  plan: string
  provider: "Anthropic" | "OpenAI"
  model: string
  priceUsd: number
  usedUsd: number
  quotaNote: string
}
export const PLAN_VALUE: PlanValueRow[] = [
  { plan: "Claude $200", provider: "Anthropic", model: "Fable 5.1", priceUsd: 200, usedUsd: 2485, quotaNote: "50% of quota left" },
  { plan: "OpenAI $200", provider: "OpenAI", model: "GPT-6 Astra", priceUsd: 200, usedUsd: 2897, quotaNote: "quota used up" },
]

/** Subscription gross margin by model and utilization (SemiAnalysis). Fable at full use is "about 1%". */
export type MarginRow = { model: "Opus 5.5" | "Fable 5.1"; utilization: "100%" | "20%"; marginPct: number; approx: boolean }
export const MARGINS: MarginRow[] = [
  { model: "Opus 5.5", utilization: "100%", marginPct: -369, approx: false },
  { model: "Fable 5.1", utilization: "100%", marginPct: 1, approx: true },
  { model: "Opus 5.5", utilization: "20%", marginPct: 6, approx: false },
  { model: "Fable 5.1", utilization: "20%", marginPct: 80, approx: false },
]
